#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db83fd849ccc1043728e8ea46d0036ea0e")]
public partial class DBDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  #endregion
	
	public DBDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db83fd849ccc1043728e8ea46d0036ea0eConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ESP_eCode")]
	public ISingleResult<ESP_eCodeResult> ESP_eCode()
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		return ((ISingleResult<ESP_eCodeResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ESP_Login")]
	public ISingleResult<ESP_LoginResult> ESP_Login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string uid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(40)")] string pwd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(15)")] string ip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SessID", DbType="VarChar(50)")] string sessID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(140)")] string url, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(140)")] string ecode)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uid, pwd, ip, sessID, url, ecode);
		return ((ISingleResult<ESP_LoginResult>)(result.ReturnValue));
	}
}

public partial class ESP_eCodeResult
{
	
	private string _CodeSubTypeDesp;
	
	public ESP_eCodeResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeSubTypeDesp", DbType="NVarChar(140)")]
	public string CodeSubTypeDesp
	{
		get
		{
			return this._CodeSubTypeDesp;
		}
		set
		{
			if ((this._CodeSubTypeDesp != value))
			{
				this._CodeSubTypeDesp = value;
			}
		}
	}
}

public partial class ESP_LoginResult
{
	
	private System.Nullable<char> _cflag;
	
	private string _cDesp;
	
	private string _username;
	
	private string _DeptID;
	
	private string _Ruid;
	
	public ESP_LoginResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cflag", DbType="Char(1)")]
	public System.Nullable<char> cflag
	{
		get
		{
			return this._cflag;
		}
		set
		{
			if ((this._cflag != value))
			{
				this._cflag = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cDesp", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string cDesp
	{
		get
		{
			return this._cDesp;
		}
		set
		{
			if ((this._cDesp != value))
			{
				this._cDesp = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(20)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this._username = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeptID", DbType="Char(3)")]
	public string DeptID
	{
		get
		{
			return this._DeptID;
		}
		set
		{
			if ((this._DeptID != value))
			{
				this._DeptID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ruid", DbType="VarChar(20)")]
	public string Ruid
	{
		get
		{
			return this._Ruid;
		}
		set
		{
			if ((this._Ruid != value))
			{
				this._Ruid = value;
			}
		}
	}
}
#pragma warning restore 1591
